import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const profiles = sqliteTable("profiles", {
  token: text("token").primaryKey(),
  username: text("username").notNull(),
  passcode: text("passcode"),
  rating: integer("rating").notNull().default(1000),
  points: integer("points").notNull().default(0),
  wins: integer("wins").notNull().default(0),
  losses: integer("losses").notNull().default(0),
  draws: integer("draws").notNull().default(0),
  role: text("role").notNull().default("user"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const rooms = sqliteTable("rooms", {
  code: text("code").primaryKey(),
  hostName: text("host_name").notNull(),
  hostToken: text("host_token").notNull(),
  guestName: text("guest_name"),
  guestToken: text("guest_token"),
  boardJson: text("board_json").notNull(),
  turn: text("turn").notNull().default("white"),
  forcedFrom: integer("forced_from"),
  winner: text("winner"),
  status: text("status").notNull().default("waiting"),
  mode: text("mode").notNull().default("casual"),
  wagerAmount: integer("wager_amount").notNull().default(0),
  escrowId: text("escrow_id"),
  leagueId: text("league_id"),
  matchId: text("match_id"),
  moveCount: integer("move_count").notNull().default(0),
  resultApplied: integer("result_applied").notNull().default(0),
  lastMoveTime: integer("last_move_time").notNull().default(0),
  disconnectTime: integer("disconnect_time"),
  disconnectedPlayer: text("disconnected_player"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const walletTransactions = sqliteTable("wallet_transactions", {
  id: text("id").primaryKey(),
  userToken: text("user_token").notNull(),
  type: text("type").notNull(),
  currency: text("currency").notNull(),
  amount: integer("amount").notNull(),
  reference: text("reference").notNull(),
  status: text("status").notNull().default("completed"),
  metaJson: text("meta_json").notNull().default("{}"),
  createdAt: text("created_at").notNull(),
});

export const leagues = sqliteTable("leagues", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  entryFeePoints: integer("entry_fee_points").notNull().default(0),
  prizePoolPoints: integer("prize_pool_points").notNull().default(0),
  status: text("status").notNull().default("registration"),
  format: text("format").notNull().default("single_elimination"),
  facilitatorToken: text("facilitator_token").notNull(),
  facilitatorName: text("facilitator_name").notNull(),
  maxParticipants: integer("max_participants").notNull().default(16),
  winnerToken: text("winner_token"),
  winnerName: text("winner_name"),
  runnerUpToken: text("runner_up_token"),
  runnerUpName: text("runner_up_name"),
  thirdPlaceToken: text("third_place_token"),
  thirdPlaceName: text("third_place_name"),
  isPrivate: integer("is_private").notNull().default(0),
  inviteCode: text("invite_code"),
  requiresApproval: integer("requires_approval").notNull().default(0),
  scheduleDate: text("schedule_date"),
  scheduleTime: text("schedule_time"),
  gameDays: text("game_days"),
  turnTimerSeconds: integer("turn_timer_seconds").notNull().default(60),
  roundsCount: integer("rounds_count").notNull().default(0),
  prizeDistributionJson: text("prize_distribution_json").notNull().default('{"first":60,"second":30,"third":10}'),
  rulesNotes: text("rules_notes"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const leagueParticipants = sqliteTable("league_participants", {
  id: text("id").primaryKey(),
  leagueId: text("league_id").notNull(),
  userToken: text("user_token").notNull(),
  username: text("username").notNull(),
  status: text("status").notNull().default("approved"),
  seed: integer("seed").notNull().default(0),
  checkedIn: integer("checked_in").notNull().default(0),
  pointsScore: integer("points_score").notNull().default(0),
  winsCount: integer("wins_count").notNull().default(0),
  lossesCount: integer("losses_count").notNull().default(0),
  drawsCount: integer("draws_count").notNull().default(0),
  joinedAt: text("joined_at").notNull(),
});

export const leagueMatches = sqliteTable("league_matches", {
  id: text("id").primaryKey(),
  leagueId: text("league_id").notNull(),
  round: integer("round").notNull(),
  matchNumber: integer("match_number").notNull(),
  bracketType: text("bracket_type").notNull().default("winners"),
  player1Token: text("player1_token"),
  player1Name: text("player1_name"),
  player1Score: integer("player1_score").notNull().default(0),
  player2Token: text("player2_token"),
  player2Name: text("player2_name"),
  player2Score: integer("player2_score").notNull().default(0),
  winnerToken: text("winner_token"),
  roomCode: text("room_code"),
  scheduledTime: text("scheduled_time"),
  status: text("status").notNull().default("pending"),
  disputeNotes: text("dispute_notes"),
  createdAt: text("created_at").notNull(),
});

export const escrows = sqliteTable("escrows", {
  id: text("id").primaryKey(),
  roomCode: text("room_code").notNull(),
  amountPoints: integer("amount_points").notNull(),
  player1Token: text("player1_token").notNull(),
  player2Token: text("player2_token"),
  lockedAt: text("locked_at").notNull(),
  status: text("status").notNull().default("locked"),
  winnerToken: text("winner_token"),
  disbursedAt: text("disbursed_at"),
});

export const adminLogs = sqliteTable("admin_logs", {
  id: text("id").primaryKey(),
  adminToken: text("admin_token").notNull(),
  adminName: text("admin_name").notNull(),
  action: text("action").notNull(),
  target: text("target").notNull(),
  detailsJson: text("details_json").notNull().default("{}"),
  createdAt: text("created_at").notNull(),
});
